name: deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up git account
      run: |
        git config --local user.email ${{ secrets.EMAIL }}
        git config --local user.name "ijemmao"
    - name: Deploy Heroku
      run: |
        git add .
        git commit --amend --no-edit
        git push heroku master --force
