name: deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0 
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PUSH_TOKEN }}
    - name: Deploy Heroku
      uses: akhileshns/heroku-deploy@v3.5.7
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} # Must be unique in Heroku
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        procfile: "web: yarn start"
